# Generated by Django 5.2.5 on 2026-03-13 21:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Post Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Job Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='organization.department', verbose_name='Department')),
                ('parent_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_posts', to='organization.organizationalpost', verbose_name='Parent Post (Manager)')),
            ],
            options={
                'verbose_name': 'Organizational Post',
                'verbose_name_plural': 'Organizational Posts',
            },
        ),
    ]
