# Generated by Django 5.2.5 on 2026-03-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_person_personposthistory_delete_employeeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='personposthistory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
