# Generated by Django 5.2.5 on 2026-03-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_personposthistory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
    ]
