# Generated by Django 5.2.5 on 2026-04-25 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_remove_competency_category_delete_competencycategory'),
        ('organization', '0005_person_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalpost',
            name='competency_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizational_posts', to='assessments.competencylevel', verbose_name='Competency Level'),
        ),
    ]
