# Generated by Django 5.2.5 on 2026-04-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organizationalpost_competency_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Employee Code'),
        ),
    ]
