# Generated by Django 5.2.5 on 2026-05-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_person_employee_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalpost',
            name='competency_level',
        ),
    ]
