# Generated by Django 5.2.5 on 2026-05-03 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_remove_organizationalpost_competency_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Management Level')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('level_number', models.PositiveIntegerField(default=1, help_text='Higher number = higher rank', verbose_name='Level Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Management Level',
                'verbose_name_plural': 'Management Levels',
                'ordering': ['-level_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PostLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Level Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post Level',
                'verbose_name_plural': 'Post Levels',
                'ordering': ['order', 'name'],
            },
        ),
    ]
