# Generated by Django 5.2.5 on 2026-05-03 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_managementlevel_postlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalpost',
            name='post_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='organization.postlevel', verbose_name='Post Level'),
        ),
    ]
