# Generated by Django 5.2.5 on 2026-03-13 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension_scores', models.JSONField(default=dict, verbose_name='Dimension Scores')),
                ('total_score', models.FloatField(default=0.0, verbose_name='Total Score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Evaluated User')),
                ('evaluator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Evaluator')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_score', to='forms.formsubmission', verbose_name='Form Submission')),
            ],
            options={
                'verbose_name': 'Assessment Score',
                'verbose_name_plural': 'Assessment Scores',
            },
        ),
    ]
