# Generated by Django 5.2.5 on 2026-03-14 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='CompetencyLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Level Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Competency Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='assessments.competencycategory')),
            ],
        ),
        migrations.CreateModel(
            name='CompetencyIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dynamic Data')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='assessments.competency')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='assessments.competencylevel')),
            ],
            options={
                'verbose_name': 'Competency Indicator',
                'verbose_name_plural': 'Competency Indicators',
                'unique_together': {('competency', 'level')},
            },
        ),
    ]
