# Generated by Django 5.2.5 on 2026-03-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_competencycategory_competencylevel_competency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competency',
            name='category',
        ),
        migrations.DeleteModel(
            name='CompetencyCategory',
        ),
    ]
