# Generated by Django 5.2.5 on 2026-04-25 22:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_remove_competency_category_delete_competencycategory'),
        ('organization', '0006_organizationalpost_competency_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCompetency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('weight', models.PositiveIntegerField(default=1, help_text='Importance of this competency for the post', verbose_name='Weight')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_competencies', to='assessments.competencylevel')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='assessments.competency')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='organization.organizationalpost')),
            ],
            options={
                'verbose_name': 'Post Competency',
                'verbose_name_plural': 'Post Competencies',
                'unique_together': {('post', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='PostCompetencyLikertScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Likert scale value 1-5', verbose_name='Score')),
                ('definition', models.TextField(help_text='Description of what this score means for this competency at this post level', verbose_name='Definition')),
                ('post_competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likert_scales', to='assessments.postcompetency')),
            ],
            options={
                'verbose_name': 'Post Competency Likert Scale',
                'verbose_name_plural': 'Post Competency Likert Scales',
                'unique_together': {('post_competency', 'score')},
            },
        ),
    ]
