# Generated by Django 5.2.5 on 2026-04-26 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_postcompetency_postcompetencylikertscale'),
        ('organization', '0006_organizationalpost_competency_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcompetency',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='postcompetency',
            unique_together={('post', 'competency', 'level')},
        ),
    ]
