# Generated by Django 5.2.5 on 2026-04-27 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_postcompetency_unique_together_and_more'),
        ('organization', '0008_remove_organizationalpost_competency_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcompetency',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='postcompetency',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='organization.organizationalpost'),
        ),
        migrations.AddConstraint(
            model_name='postcompetency',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('post', 'competency', 'level'), name='unique_post_competency_level'),
        ),
    ]
