# Generated by Django 5.2.5 on 2026-05-02
# This migration is now a no-op because level field was added in 0004

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_postcompetency_unique_together_and_more'),
    ]

    operations = [
        # No operations - level field already exists from 0004
    ]
