# Generated by Django 5.2.5 on 2026-05-03 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_add_level_to_postcompetency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcompetency',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_competencies', to='assessments.competencylevel', verbose_name='Level'),
        ),
    ]
