# Generated by Django 5.2.5 on 2026-05-03 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_alter_postcompetency_level'),
        ('organization', '0010_organizationalpost_post_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcompetency',
            name='post_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='organization.postlevel'),
        ),
        migrations.AddConstraint(
            model_name='postcompetency',
            constraint=models.UniqueConstraint(condition=models.Q(('post_level__isnull', False)), fields=('post_level', 'competency', 'level'), name='unique_post_level_competency_level'),
        ),
    ]
