# Generated by Django 5.2.5 on 2026-03-14 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0003_remove_competency_category_delete_competencycategory'),
        ('organization', '0003_person_personposthistory_delete_employeeprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Template Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicators', models.ManyToManyField(blank=True, to='assessments.competencyindicator', verbose_name='Selected Competencies (Matrix Cells)')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_templates', to='assessments.competencylevel', verbose_name='Job Level')),
            ],
            options={
                'verbose_name': 'Interview Template',
                'verbose_name_plural': 'Interview Templates',
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Session Title')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Interview Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL, verbose_name='Interviewer')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='interviews.interviewtemplate', verbose_name='Interview Template')),
            ],
            options={
                'verbose_name': 'Interview Session',
                'verbose_name_plural': 'Interview Sessions',
            },
        ),
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluation_data', models.JSONField(blank=True, default=dict, verbose_name='Evaluation Data')),
                ('total_score', models.FloatField(default=0.0, verbose_name='Total Score')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_evaluations', to='organization.person', verbose_name='Evaluated Person')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='interviews.interviewsession', verbose_name='Interview Session')),
            ],
            options={
                'verbose_name': 'Interview Evaluation',
                'verbose_name_plural': 'Interview Evaluations',
                'unique_together': {('session', 'evaluated_person')},
            },
        ),
    ]
