# Generated by Django 5.2.5 on 2026-04-28 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_postcompetency_unique_together_and_more'),
        ('files', '0003_remove_filearchive_interview_session'),
        ('interviews', '0001_initial'),
        ('organization', '0007_person_employee_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='interviewer',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='template',
        ),
        migrations.RemoveField(
            model_name='interviewtemplate',
            name='indicators',
        ),
        migrations.RemoveField(
            model_name='interviewtemplate',
            name='level',
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان جلسه')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ مصاحبه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interviews', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('evaluated_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews_as_evaluated', to='organization.person', verbose_name='فرد ارزیابی\u200cشونده')),
                ('evaluated_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='organization.organizationalpost', verbose_name='پست ارزیابی\u200cشونده')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews_as_interviewer', to='organization.person', verbose_name='مصاحبه\u200cشونده (ارزیابی\u200cکننده)')),
            ],
            options={
                'verbose_name': 'مصاحبه',
                'verbose_name_plural': 'مصاحبه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='نمره')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('selected_definition', models.TextField(blank=True, null=True, verbose_name='تعریف انتخاب شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_responses', to='assessments.competency', verbose_name='شایستگی')),
                ('competency_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_responses', to='assessments.competencylevel', verbose_name='سطح شایستگی')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interviews.interview', verbose_name='مصاحبه')),
            ],
            options={
                'verbose_name': 'پاسخ مصاحبه',
                'verbose_name_plural': 'پاسخ\u200cهای مصاحبه',
                'ordering': ['competency__name', 'competency_level__order'],
                'unique_together': {('interview', 'competency', 'competency_level')},
            },
        ),
        migrations.DeleteModel(
            name='InterviewEvaluation',
        ),
        migrations.DeleteModel(
            name='InterviewSession',
        ),
        migrations.DeleteModel(
            name='InterviewTemplate',
        ),
    ]
