# Generated by Django 5.2.5 on 2026-05-02 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_postcompetency_unique_together_and_more'),
        ('interviews', '0002_remove_interviewsession_interviewer_and_more'),
        ('organization', '0007_person_employee_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='evaluated_person',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='evaluated_post',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interviewer',
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('planned', 'برنامه\u200cریزی شده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده')], default='planned', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='InterviewParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='interviews.interview', verbose_name='جلسه مصاحبه')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_participations', to='organization.person', verbose_name='مصاحبه\u200cشونده (ارزیابی\u200cکننده)')),
                ('interviewer_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_participations', to='organization.organizationalpost', verbose_name='پست مصاحبه\u200cشونده')),
            ],
            options={
                'verbose_name': 'شرکت\u200cکننده مصاحبه',
                'verbose_name_plural': 'شرکت\u200cکنندگان مصاحبه',
                'ordering': ['interviewer__first_name', 'interviewer__last_name'],
                'unique_together': {('interview', 'interviewer')},
            },
        ),
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='نمره')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('selected_definition', models.TextField(blank=True, null=True, verbose_name='تعریف انتخاب شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_evaluations', to='assessments.competency', verbose_name='شایستگی')),
                ('competency_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_evaluations', to='assessments.competencylevel', verbose_name='سطح شایستگی')),
                ('evaluated_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to='organization.person', verbose_name='فرد ارزیابی\u200cشونده')),
                ('evaluated_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to='organization.organizationalpost', verbose_name='پست ارزیابی\u200cشونده')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='interviews.interviewparticipant', verbose_name='شرکت\u200cکننده')),
            ],
            options={
                'verbose_name': 'ارزیابی',
                'verbose_name_plural': 'ارزیابی\u200cها',
                'ordering': ['evaluated_person__first_name', 'competency__name'],
                'unique_together': {('participant', 'evaluated_person', 'competency', 'competency_level')},
            },
        ),
        migrations.DeleteModel(
            name='InterviewResponse',
        ),
    ]
