# Generated by Django 5.2.5 on 2026-05-05 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_remove_interview_evaluated_person_and_more'),
        ('organization', '0010_organizationalpost_post_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewparticipant',
            name='interviewer_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_participations', to='organization.organizationalpost', verbose_name='پست مصاحبه\u200cشونده'),
        ),
    ]
