# Generated by Django 5.2.5 on 2026-05-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_postcompetency_post_level_and_more'),
        ('interviews', '0004_alter_interviewparticipant_interviewer_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewevaluation',
            name='competency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_evaluations', to='assessments.competency', verbose_name='شایستگی'),
        ),
        migrations.AlterField(
            model_name='interviewevaluation',
            name='competency_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_evaluations', to='assessments.competencylevel', verbose_name='سطح شایستگی'),
        ),
    ]
