# Generated by Django 5.2.5 on 2026-03-13 20:25

import apps.files.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.files.models.user_directory_path, verbose_name='File')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Content Type')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Size (bytes)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'File Archive',
                'verbose_name_plural': 'File Archives',
            },
        ),
    ]
