# Generated by Django 5.2.5 on 2026-03-14 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filearchive',
            name='interview_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_files', to='interviews.interviewsession', verbose_name='Interview Session'),
        ),
    ]
