# Generated by Django 5.2.5 on 2026-04-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_filearchive_interview_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filearchive',
            name='interview_session',
        ),
    ]
