# Generated by Django 5.2.5 on 2026-04-28 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_filearchive_interview_session'),
        ('interviews', '0002_remove_interviewsession_interviewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filearchive',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_files', to='interviews.interview', verbose_name='مصاحبه'),
        ),
    ]
